server:
  port: 13001
spring:
  application:
    name: admin-server
  #\u8BBE\u7F6E\u767B\u5F55\u4FE1\u606F
  security:
    user:
      name: "admin"
      password: "admin"
eureka:
  client:
    #eureka client\u95F4\u9694\u591A\u4E45\u53BB\u62C9\u53D6\u670D\u52A1\u6CE8\u518C\u4FE1\u606F
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://eureka-one:10001/eureka/,http://eureka-two:10002/eureka/,http://eureka-three:10003/eureka/
  instance:
    #\u7B49\u5F85\u5FC3\u8DF3\u8D85\u65F6\u65F6\u95F4
    lease-renewal-interval-in-seconds: 10
    #\u5065\u5EB7\u76D1\u63A7\u8DEF\u5F84
    health-check-url-path: /actuator/health
    #\u5143\u6570\u636E
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
management:
  #\u7AEF\u70B9
  endpoints:
    web:
      #\u66B4\u9732
      exposure:
        include: "*"
  endpoint:
    #\u5065\u5EB7\u60C5\u51B5
    health:
      #\u8BE6\u7EC6\u7A0B\u5EA6
      show-details: always