#\u7AEF\u53E3\u53F7
server:
  port: 11001
spring:
  application:
    # \u5E94\u7528\u540D
    name: config-server
  cloud:
    config:
      server:
        git:
          # \u4ED3\u5E93\u5730\u5740
          uri: https://github.com/Very666/JMDZ-DEMO
          # \u914D\u7F6E\u6587\u4EF6\u76F8\u5BF9\u8DEF\u5F84
          search-paths: config-repo
      # \u5FEB\u901F\u5931\u8D25
      fail-fast: true
    bus:
      # \u5F00\u542F\u603B\u7EBF
      enabled: true
      # \u5F00\u542F\u8DDF\u8E2A
      trace:
        enabled: true
# \u6CE8\u518C\u5230euerka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-one:10001/eureka/,http://eureka-two:10002/eureka/,http://eureka-three:10003/eureka/
management:
 # \u66B4\u9732\u7AEF\u70B9
  endpoints:
    web:
      exposure:
        include: bus-refresh