spring:
  # 定义项目名称
  application:
    name: eureka-three

# 定义端口
server:
  port: 10003
eureka:
  instance:
    hostname: eureka-three
  client:
    # 是否注册到euerka
    register-with-eureka: false
    # 是否从euerka获取注册信息
    fetch-registry: false
    # euerka服务地址
    service-url:
     defaultZone: http://eureka-one:10001/eureka/,http://eureka-two:10002/eureka/



