spring:
  # \u5B9A\u4E49\u9879\u76EE\u540D\u79F0
  application:
    name: eureka-one

# \u5B9A\u4E49\u7AEF\u53E3
server:
  port: 10001
eureka:
  instance:
    hostname: eureka-one
  client:
    # \u662F\u5426\u6CE8\u518C\u5230euerka
    register-with-eureka: false
    # \u662F\u5426\u4ECEeuerka\u83B7\u53D6\u6CE8\u518C\u4FE1\u606F
    fetch-registry: false
    # euerka\u670D\u52A1\u5730\u5740
    service-url:
     defaultZone: http://eureka-two:10002/eureka/,http://eureka-three:10003/eureka/



